import { PropsWithChildren } from 'react';
import Navbar from './components/nav/navbar';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function Layout({ children }: PropsWithChildren) {
    return (
        <div className="border-blue-700">
            <Navbar></Navbar>
            <main>{children}</main>

            {/* <html lang="en">
            <body>
                <Navbar></Navbar>
            </body>
            </html> */}
        </div>
    );
}
